### ISSUE TITLE
[BUG] Quick Filter is searching more than just the title

### ISSUE THREAD

**Issue by adamfowlerit** [adamfowlerit/msportals.io#111]
Type 'sec' in the quick filter, and other results come up that don't contain 'sec' in the display name.

**Comment by PsychoData** [comment]
This is actually somewhat by design, because this way it can also search
the URLs to find things like

"MFA registration" for "mfasetup" from matching "https://aka.ms/mfasetup"

**Comment by adamfowlerit** [comment]
It seems to be picking up the span class though as @mdjx pointed out to me - "span class=portal-secondary-urls", so anything wit ha secondary url gets picked up with the search 'sec'

Great to have it searching the secondary urls, but not the code behind it!

**Comment by mdjx** [comment]
This should do it, instead of just looking at `innerHTML` it now builds a string containing the `innerText` and all `href` data, then uses that string for the searching.

**Comment by PsychoData** [comment]
This brings up another point I was thinking about - it might be useful to have a place just for general other terms for it to match, or maybe "term mappings" ? 

I was thinking options like 

1) a span named "PortalTerms" for additional terms for it to match, 
2) "search term" mappings, so if someone searches "Intune" our Search program also searches "device management" or something similar

Suggestion 1 (search terms) seems to be easier to implement as 2 would need more maintenance/tweaking. 
Note that no current entries have a "Search terms" item in them, so this is only for when that gets added 

For example - these items all could be somewhat related to Intune

![image](https://user-images.githubusercontent.com/3719116/112002547-61a93880-8af6-11eb-87ae-529c6f5e04da.png)

but if you search for "Intune" you get just two
![image](https://user-images.githubusercontent.com/3719116/112002746-99b07b80-8af6-11eb-85f7-12b5f9fb17e4.png)

and the "Endpoint Manager Admin Console" is only matching because of that Note of "Intune" 
I was thinking we could add a "search terms" item for any additional useful terms for the URL to match? 

Here is a local test **without this proposed commit** where I added a Span "portal-searchterms", set it to Display:None in CSS, and searched for "Sample" to match it 

![image](https://user-images.githubusercontent.com/3719116/112003728-8a7dfd80-8af7-11eb-91e6-d2576343877e.png)
![image](https://user-images.githubusercontent.com/3719116/112004071-d8930100-8af7-11eb-9731-21dec8f3e47c.png)

however, since it isn't "visible" text (`display:none`) it doesn't return in InnerText, it won't still match for the "innerText" search (though it will for the current search, this would be broken after this Commit's change) 

![image](https://user-images.githubusercontent.com/3719116/112006221-e6e21c80-8af9-11eb-9194-e761cb53e286.png)

**Comment by adamfowlerit** [comment]
Do we go down the path of search terms, or just an extra keyword match on certain portal entries? That might be easier to manage? I've merged the first changes @mdjx did and that appears to be working.

I would still like to see a single page with all the portals on too :)
