### ISSUE TITLE
[MissingPortal] Product feedback (tenant) 

### ISSUE THREAD

**Issue by GruberMarkus** [adamfowlerit/msportals.io#200]
## Portal Name ##
Product feedback

## Portal URL ##
https://admin.microsoft.com/AdminPortal/Home#/tenantfeedback

## What portal page and section would this fit best on? ##
/_data/portals/admin.json

## Special Notes ##
When your users send feedback, you can read and manage it here. Users can send feedback in Microsoft 365 products about their experience. Feedback is refreshed hourly. You might not see feedback on all products in this list.

**Comment by adamfowlerit** [comment]
This is a sub-link of a portal - I don't mind when it's a key product (like Azure Sentinel) but if we linked every sub portal we'd have a lot more links to manage. I'll wait for your response before closing.

**Comment by GruberMarkus** [comment]
I agree with you. What do you think about adding the description of the sub portal to the main portal?

**Comment by adamfowlerit** [comment]
Same applies as above - if we add this, we'd need to add every other component of each portal. We've done it for Azure a bit, but usually for very mainstream and specific subsites because everything's a subsite there.

I'd more consider putting a bunch of keywords against each portal, if you were looking for a particular feature to know which portal it's in - still work, maybe less so but would also require a lot of work.

**Comment by GruberMarkus** [comment]
I'm in with the keyword idea.

**Comment by adamfowlerit** [comment]
I went through an excercise of adding each subportal to a certain area which took a lot of work but received zero feedback. Unless someone wants to put the effort behind adding all these as links or keywords (which on reflection there'd just be too many keywords) then I'm going to close this one. I would love to see every single subportal link, but it's just a huge ask to maintain that across every portal.
