### ISSUE TITLE
Favorites Icons not showing

### ISSUE THREAD

**Issue by adamfowlerit** [adamfowlerit/msportals.io#232]
## Describe the bug ##

In the Favorites section, links saved have just text for the icons (such as aka.ms or B2B)

## To Reproduce ##

Add a site to favorites that has icons
Go to favorites.

## Expected behavior ##

Icons should be showing

## Screenshots ##

![image](https://github.com/adamfowlerit/msportals.io/assets/18343337/972d0445-2fe0-4f85-9437-503607c07f1c)

**Comment by PsychoData** [comment]
This will be an artifact of how it copies to the favorites page.... hmmm... 
I think I might be able to copy it over with some different code instead, so that it will maintain the icons instead. 

I'll look at it tomorrow

**Comment by PsychoData** [comment]
fixed in https://github.com/adamfowlerit/msportals.io/commit/84af43c61b449bf49a34010c21742d4f26474e8d

Luckily, this is actually stored in the "Saved" pages as JSON, so this should retro-actively fix any that were previously saved as well! 
Your browser may try to cache the old version of the HTML, but testing with InPrivate mode, or clearing your browser cache should fix it if you are still seeing this 😄 
![gml2Y6k 1](https://github.com/adamfowlerit/msportals.io/assets/3719116/a803a6a6-fee0-4cbb-8618-2b0df45a3f3e)
