### ISSUE TITLE
[BUG] Short Bug Description

### ISSUE THREAD

**Issue by adamfowlerit** [adamfowlerit/msportals.io#282]
Shortcut links to sections such as:
https://msportals.io/training?search=#data-and-ai-microsoft-certified-microsoft-fabric-data-engineerin

don't actually jump to the section. This will work if you've clicked the shortcut link once, but not on a fresh visit to the page, or refresh.

**Comment by jlaundry** [comment]
(It currently works in Firefox, it doesn't in Edge/Chrome).

The issue is the inline JavaScript, line 144: `Uncaught (in promise) TypeError: document.getElementsByClassName(...)[0] is undefined`

On other pages, there is a hidden `.nomatches` div, which is created by the `default.html` template:

https://github.com/adamfowlerit/msportals.io/blob/8712dde085ff2de18bb184a8530c9ee66da4b6bb/_layouts/default.html#L70-L72

The problem is, the Training and Licensing `page.title` doesn't include the magic word "Portals".

**Comment by adamfowlerit** [comment]
Champ! Thank you very much :)
